name: Build

on:
  push:
    branches: ["main"]

env:
  GOPRIVATE: github.com/hidromatologia-v2/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - run: git config --global url.https://${{ secrets.GH_TOKEN }}:x-oauth-basic@github.com/hidromatologia-v2/models.insteadOf https://github.com/hidromatologia-v2/models

      - name: Prepare vendor directory
        run: go mod vendor

      - name: Set up docker environment
        run: docker compose up -d

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Clean docker environment
        run: docker compose down --rmi all -v --remove-orphans

      - name: Clean vendor directory
        run: rm -r vendor

  versioning:
    permissions:
      contents: write
    needs: test
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.latest_version.outputs.version }}
    steps:
      - uses: actions/checkout@v3

      - name: Git Identity
        run: |
          git checkout main
          git fetch --all --tags
          git config --global user.email "antoniojosedonishung@gmail.com"
          git config --global user.name "Antonio Donis"

      - name: Setup node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"

      - name: Changelog
        run: 'npx standard-version --message "[ci skip] chore(release): %s"'

      - name: Push changes
        run: git push --follow-tags --force origin main

      - id: latest_version
        name: Latest version
        run: python version.py >> $GITHUB_OUTPUT

  release-github:
    permissions:
      contents: write
      packages: write
    needs:
      - versioning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: git config --global url.https://${{ secrets.GH_TOKEN }}:x-oauth-basic@github.com/hidromatologia-v2/models.insteadOf https://github.com/hidromatologia-v2/models

      - name: Prepare vendor directory
        run: go mod vendor

      - name: GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{needs.versioning.outputs.version}}

      - name: Clean vendor directory
        run: rm -r vendor

  release-docker:
    needs:
      - versioning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker image
        run: echo "v${{needs.versioning.outputs.version}}"

      - run: git config --global url.https://${{ secrets.GH_TOKEN }}:x-oauth-basic@github.com/hidromatologia-v2/models.insteadOf https://github.com/hidromatologia-v2/models

      - name: Prepare vendor directory
        run: go mod vendor

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:${{needs.versioning.outputs.version}}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Clean vendor directory
        run: rm -r vendor
