name: Coverage

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed

permissions: read-all

env:
  GOPRIVATE: github.com/hidromatologia-v2/*
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - run: git config --global url.https://$GH_TOKEN@github.com/hidromatologia-v2.insteadOf https://github.com/hidromatologia-v2

      - name: Prepare vendor directory
        run: go mod vendor

      - name: Set up docker environment
        run: docker compose up -d

      - name: Test
        run: go test -coverpkg ./... -coverprofile coverage.txt -covermode atomic ./...

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt
          fail_ci_if_error: true

      - name: Clean docker environment
        run: docker compose down --rmi all -v --remove-orphans

      - name: Clean vendor directory
        run: rm -r vendor
